AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFront CDN Configuration'

Resources:
  WebsiteCDN:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        Origins:
          - DomainName: !Ref 'WebsiteDomain'
            Id: Website
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: Website
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          MinTTL: 0
          DefaultTTL: 3600
          MaxTTL: 86400
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none